apiVersion: v1

Kind: Pod

metadata:
  name: my-first-app
  labels:
    app: my-app


spec:
  containers:
    - name: nginx-container
      image: nginx


---
apiVersion: apps/v1
Kind: ReplicaSet
metadata:
  name: replicaset-front
  labels:
    app: frontend
    type: replica
spec:
 - template:
     metadata:
       name: my-first-app
       labes:
         app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
replicas: 3 
selector: 
  matchLabels: 
    app: my-app