version: '3.7'
services:
  ggi-be:
    container_name: ggi-be 
    image: registry.gitlab.com/grupojaque/ggi-real-estate/ggi-journey-be:development.178378c7
    #build: .
    #volumes: 
    #  - $PWD:/app
    env_file:
      - ./ggi-dev.env
    ports:
      - "3040:3040"
    networks:
      ggi-be:
        ipv4_address: 172.24.0.2 
  proxy_ggi:
    image: nginx:1.19.2-alpine
    container_name: proxy_ssl
    ports:
      - "80:80"
    volumes:
      - ./default-global-http.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - ggi-be
networks: 
  ggi-be:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
#  redis:
#    container_name: redis
#    image: redis 
#    ports:
 #     - "6379:6379"
  

