version: '3'
services:
  moodle_db:
    image: mysql:5.7
    container_name: moodle_db
    ports: 
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=user # the name of the database user
      - MYSQL_PASSWORD=password # the password of the mysql user
    volumes:
      - /data/database/moodle/data:/var/lib/mysql
      - /data/database/moodle/initdb.d:/docker-entrypoint-initdb.d
    restart: always    
    networks:
      moodle:
        ipv4_address: 172.24.0.2        
  moodle_web:
    image: bitnami/moodle:3
    container_name: moodle
    ports:
      - '80:8080'
      - '443:8443'
    restart: always
    #links:
    # - moodle_db:mysql
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD= admin
      - MOODLE_EMAIL=admin@programster.org      
      - MOODLE_DATABASE_HOST=moodle_db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=user
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=password
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      moodle:
        ipv4_address: 172.24.0.4
    volumes:
      - /data/moodle_data:/bitnami
            #- /data/moodle/content/web:/bitnami/moodle
            #- /data/moodle/content/moodledata:/bitnami/moodledata
    depends_on:
      - moodle_db

networks:
  moodle:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
