version: '3'

services:
  wordpress_db:
    image: mysql:5.7
    container_name: wordpress_db
    ports:
      - "3308:3306"
    volumes:
      - /mysql_data/database/wordpress/data:/var/lib/mysql
      - /mysql_data/database/wordpress/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: u21q2w3e.4sT # any random string will do
      MYSQL_DATABASE: wordpress # the name of your mysql database
      MYSQL_USER: user_wordpress # the name of the database user
      MYSQL_PASSWORD: P4ssWordpress # the password of the mysql user
    networks:
      wordpress:
        ipv4_address: 172.24.0.2
  wordpress_web:
    depends_on:
      - wordpress_db
    image: wordpress:php7.4 # we're using the image with php7.4
    container_name: wordpress
    ports:
      - "8080:80"
    restart: always
    links:
      - wordpress_db:mysql
    volumes:
      - /site_data/web/wordpress/src:/var/www/html
    networks:
      wordpress:
        ipv4_address: 172.24.0.4
  proxy_ssl:
    image: nginx:1.19.2-alpine
    container_name: proxy_ssl
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/dand.info/fullchain.pem:/etc/letsencrypt/live/dand.info/fullchain.pem
      - /etc/letsencrypt/live/dand.info/privkey.pem:/etc/letsencrypt/live/dand.info/privkey.pem      
    restart: always
    networks:
      - wordpress

networks: 
  wordpress:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
