apiVersion: v1
kind: ConfigMap
metadata: 
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: app-config
---
# Single env
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: APP_COLOR
        valueFrom: 
          configMapKeyRef:
            name: app-config
            key: APP_COLOR 
---
# volumes
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    volumes:
    - name: app-config-volume
      comfigMap:
        name: app-config  

