apiVersion: v1
kind: Secret
metadata: 
  name: app-secret
data:
  DB_HOST: mysql 
  DB_USER: root
  DB_PASSWORD: passwd
---
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: app-secret
---
# Single env
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: DB_PASSWORD
        valueFrom: 
          configMapKeyRef:
            name: app-secret
            key: DB_PASSWORD 
---
# volumes
apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - name: nginx
    image: nginx
    volumes:
    - name: app-secret-volume
      secret:
        name: app-secret

