apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels: 
    type: front-end
    app: myapp
spec:
  template:
    metadata:
      name: 
      labels:
        app: myapp
        type: front-end
    spec: 
      containers:
      - name: nginx-container
        image: httpd:2.4-alpine 
replicas: 3
selector: 
  matchLabels:
    type: front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      labels:
        name: busybox-pod
    spec:
      containers:
      - name: busybox-container
        image: busybox888
        command:
        - sh
        - "-c"
        - echo Hello Kubernetes! && sleep 3600controlplane $






