#demonset run 1 pod in each one of the cluster
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
spec:
  selector: 
    matchLabels: 
      app: monitoring-agent
  template:
    metadata:
      labels: 
        app: monitoring-agent
    spec:
      containers:
      - name: monitoring-agent
        image: monitoring-agent
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: monitoring-demo
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata: 
      labels:
        app: monitoring-agent
    spec:
      containers:
      - name: monitoring-agent
        image: monitoring-agent
