apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::073438159894:role/EKS-Role-Bimbo
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: | 
    - userarn: arn:aws:iam::073438159894:user/david.rangel@grupojaque.com 
      username: david.rangel@grupojaque.com 
      groups: 
        - system:masters

